---
version: '3.3'
services:

######  Main application ######
  voting-service:
    build: './voting-service'
    ports: ['8080:8080']
    links:
      - mysql:mysql
      - redis:redis
    volumes:
      - '/usr/services/voting-service'
      - '/usr/scritps/wait-for-it.sh'
    depends_on: ['mysql', 'redis']

  voting-totalizer-producer-service:
    build: './voting-totalizer-producer-service'
    ports: ['8081:8081']
    links:
      - mysql:mysql
      - redis:redis
    volumes:
      - '/usr/services/voting-totalizer-producer-service'
      - '/usr/scritps/wait-for-it.sh'
    depends_on: ['mysql', 'redis']

###### Database ######
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: voting
      MYSQL_ROOT_PASSWORD: 1234

  redis:
    image: redis
    command: redis-server --requirepass redis123
    ports: ['6379:6379']

###### Messaging systems ######
  rabbitmq:
    image: rabbitmq:3.6-management
    ports: ['15672:15672']

###### Monitoring stack ######
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    ports: ['9200:9200']

  logstash:
    image: docker.elastic.co/logstash/logstash:6.5.0
    ports: ['9600:9600']
    command: logstash -f /usr/share/logstash/config/logstash.conf
    volumes:
      - './monitoring-config/logs-logstash.conf:/usr/share/logstash/config/logstash.conf'
    depends_on: ['elasticsearch']

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.0
    ports: ['5601:5601']
    depends_on: ['elasticsearch']
